[POC] Redesign settings
allegro/django-powerdns-dnssec pull request #159
Opened 2016-10-03 12:28 UTC by ar4s

Run ``local_dnsaas`` to run customized settings. Before running command copy ``dnsaas/settings/local.py.tmpl`` to ``dnsaas/settings/local.py`` and add your special settings.

2016-10-07 06:24 UTC, ghost approved these changes

2016-10-10 08:39 UTC, mkurek requested changes

2016-10-10 08:39 UTC, mkurek commented on dnsaas/settings/base.py
> +NEW_UI_ENABLED = False
True?

2016-10-12 06:08 UTC, xliiv commented on dnsaas/settings/base.py
> +NEW_UI_ENABLED = False
Will you change it to True?

2019-10-17 05:18 UTC, mzdeb commented
This project is deprecated.

2019-10-17 05:18 UTC, closed without merging